#服务器端口号
server:
  port: 8000

spring:
  #mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  #服务名称
  application:
    name: cloud-order-service
  cloud:
    #rocketmq配置
    stream:
      default-binder: rocketmq
      rocketmq:
        binder:
          name-server: 192.168.0.113:9876;192.168.0.115:9876
        bindings:
          order80-consumer:
            consumer:
              tags: 8001 || 8002
      bindings:
        order80-consumer:
          destination: payment-topic
          group: order-consumer-group
          content-type: application/json

#eureka配置
eureka:
  client:
    #讲自己注册进Eureka服务端
    register-with-eureka: true
    #是否从Eureka服务端抓取已有的注册信息，默认为true。单节点无所谓，但集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #要注册的Eureka服务端的地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

