server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  #mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  #rocketmq配置
  cloud:
    stream:
      default-binder: rocketmq
      rocketmq:
        binder:
          name-server: 192.168.0.113:9876;192.168.0.115:9876
      bindings:
        provider-payment8001-producer:
          destination: payment-topic
          content-type: application/json


#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.beyond233.springcloud.entity


#eureka配置
eureka:
  client:
    #讲自己注册进Eureka服务端
    register-with-eureka: true
    #是否从Eureka服务端抓取已有的注册信息，默认为true。单节点无所谓，但集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      defaultZnne: http://eureka7001.com:7001/eureka/
      #集群版： 要注册的所有的Eureka服务端的地址
  #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #给服务状态status起一个简洁的名
    instance-id: payment8001
    #开启后访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒，默认为30秒
    #    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒，默认为90秒，超时则将剔除未及时发送心跳的服务
#    lease-expiration-duration-in-seconds: 2