server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  #链路追踪
  zipkin:
    base-url: http://192.168.1.6:9411
  sleuth:
    sampler:
      probability: 1  #采样率值介于0和1之间，则表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.beyond233.springcloud.entity


#eureka
eureka:
  client:
    #讲自己注册进Eureka服务端
    register-with-eureka: true
    #是否从Eureka服务端抓取已有的注册信息，默认为true。单节点无所谓，但集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    #给服务状态status起一个简洁的名.
    instance-id: payment8002
    lease-renewal-interval-in-seconds: 2 #设置心跳时间间隔
    lease-expiration-duration-in-seconds: 5 #默认90秒，现在是超过5秒间隔
    prefer-ip-address: true  #访问的路径变为IP地址