server:
  port: 7001

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，自己的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #defaultZone：要注册的eureka服务端地址
      #下面为单机版：注册中心地址为自己的
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #下面为集群版：集群之间需要相互注册
#      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #关闭自我保护机制，及时剔除不可用服务
#    enable-self-preservation: false
    #时间间隔
#    eviction-interval-timer-in-ms: 2000










spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456