#Tomcat
server:
  port: 9001

#spring
spring:
  application:
    name: alibaba-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
